version: '3.7'
services:
    mysql:
        image: 'mysql:8.0'
        environment:
            MYSQL_ROOT_PASSWORD: damian
            MYSQL_PASSWORD: damian
            MYSQL_USER: damian
            MYSQL_DATABASE: newspaper
        volumes:
        - "./database:/docker-entrypoint-initdb.d"
        ports:
            # To allow the host machine to access the ports below, modify the lines below.
            # For example, to allow the host to connect to port 3306 on the container, you would change
            # "3306" to "3306:3306". Where the first port is exposed to the host and the second is the container port.
            # See https://docs.docker.com/compose/compose-file/compose-file-v3/#ports for more information.
            - '8989:3306'
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        # volumes:
        #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge